# ~/.config/foot/foot.ini

[main]

font=Hack Nerd Font Mono:size=7
font-bold=Hack Nerd Font Mono:style=Bold:size=7
font-italic=Hack Nerd Font Mono:style=Italic:size=7
font-bold-italic=Hack Nerd Font Mono:style=Bold Italic:size=7

pad=12x12

dpi-aware=yes

initial-window-size-pixels=1200x700

resize-by-cells=yes

[scrollback]

lines=100000

[cursor]

style=block
blink=yes

[colors-dark]

alpha=0.8
foreground=d8dee9
background=2e3440

regular0=3b4252
regular1=bf616a
regular2=a3be8c
regular3=ebcb8b
regular4=81a1c1
regular5=b48ead
regular6=88c0d0
regular7=e5e9f0

bright0=4c566a
bright1=bf616a
bright2=a3be8c
bright3=ebcb8b
bright4=81a1c1
bright5=b48ead
bright6=8fbcbb
bright7=eceff4

selection-foreground=2e3440
selection-background=88c0d0

urls=88c0d0

[mouse]

hide-when-typing=yes

[key-bindings]

clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

search-start=Control+Shift+r

font-increase=Control+equal Control+plus
font-decrease=Control+minus
font-reset=Control+0
