
max-gamma = 150

# Профиль на утро — в 07:00 возвращаем "identity" (т.е. фильтр выключен)
profile {
    time = 6:00
    identity = true
}

# Профиль на вечер — в 20:30 включаем тёплый фильтр
profile {
    time = 20:50
    temperature = 4000
    gamma = 0.9
}
